export const traditionalSandwiches = [
  {
    name: 'X-Salada',
    price: 8.0,
    ingredients: [
      'Carne de hambúrguer',
      'Ovo',
      'Queijo',
      'Presunto',
      'Alface',
      'Tomate',
    ],
  },
  {
    name: 'X-Salada Bacon',
    price: 12.0,
    ingredients: [
      'Carne de hambúrguer',
      'Ovo',
      'Queijo',
      'Presunto',
      'Alface',
      'Tomate',
      'Bacon',
    ],
  },
  {
    name: 'X-Salada Salsicha',
    price: 12.0,
    ingredients: [
      'Carne de hambúrguer',
      'Ovo',
      'Queijo',
      'Presunto',
      'Alface',
      'Tomate',
      'Salsicha',
    ],
  },
  {
    name: 'X-Salada Calabresa',
    price: 12.0,
    ingredients: [
      'Carne de hambúrguer',
      'Ovo',
      'Queijo',
      'Presunto',
      'Calabresa',
      'Alface',
      'Tomate',
    ],
  },
  {
    name: 'X-Salada Banana',
    price: 12.0,
    ingredients: [
      'Carne de hambúrguer',
      'Ovo',
      'Banana',
      'Queijo',
      'Presunto',
      'Alface',
      'Tomate',
    ],
  },
  {
    name: 'X-Salada Especial',
    price: 12.0,
    ingredients: [
      '2 Carne de hambúrguer',
      '2 Ovos',
      'Queijo',
      'Presunto',
      'Alface',
      'Tomate',
    ],
  },
  {
    name: 'X-Tudo Tradicional',
    price: 16.0,
    ingredients: [
      'Carne de hambúrguer',
      'Ovo',
      'Queijo',
      'Presunto',
      'Calabresa',
      'Bacon',
      'Salsicha',
      'Alface',
      'Tomate',
    ],
  },
  {
    name: 'X-Bacon',
    price: 10.0,
    ingredients: [
      'Carne de hambúrguer',
      'Bacon',
      'Queijo',
      'Presunto',
      'Alface',
      'Tomate',
    ],
  },
  {
    name: 'X-Calabresa',
    price: 10.0,
    ingredients: ['Ovo', 'Queijo', 'Presunto', 'Calabresa', 'Alface', 'Tomate'],
  },
  {
    name: 'X-Banana',
    price: 10.0,
    ingredients: [
      'Carne de hambúrguer',
      'Banana',
      'Queijo',
      'Presunto',
      'Alface',
      'Tomate',
    ],
  },
  {
    name: 'X-Egg',
    price: 7.0,
    ingredients: ['Carne de hambúrguer', 'Ovo', 'Queijo', 'Alface', 'Tomate'],
  },
  {
    name: 'X-Maionese',
    price: 7.0,
    ingredients: [
      'Carne de hambúrguer',
      'Queijo',
      'Presunto',
      'Alface',
      'Tomate',
    ],
  },
  {
    name: 'X-Burger',
    price: 6.0,
    ingredients: ['Carne de hambúrguer', 'Queijo', 'Alface', 'Tomate'],
  },
  {
    name: 'Hambúrguer',
    price: 6.0,
    ingredients: ['Carne de hambúrguer', 'Alface', 'Tomate'],
  },
  {
    name: 'Queijo',
    price: 4.0,
    ingredients: ['Pão de forma', 'Queijo'],
  },
  {
    name: 'Queijão',
    price: 7.0,
    ingredients: ['3 Pão de forma', 'Queijo'],
  },
  {
    name: 'Misto',
    price: 5.0,
    ingredients: ['Pão de forma', 'Queijo', 'Presunto'],
  },
  {
    name: 'Mistão',
    price: 7.0,
    ingredients: ['3 Pão de forma', 'Queijo', 'Presunto'],
  },
  {
    name: 'Bauru',
    price: 7.0,
    ingredients: ['Ovos', 'Queijo', 'Presunto', 'Alface', 'Tomate'],
  },
  {
    name: 'Americano',
    price: 8.0,
    ingredients: ['3 Pão de forma', 'Queijo', 'Presunto', 'Alface', 'Tomate'],
  },
];

export const topBurgers = [
  {
    name: 'Top Burg Bacon',
    price: 15.0,
    ingredients: [
      '2 Carne de hambúrguer',
      '2 Ovos',
      'Bacon',
      'Alface',
      'Tomate',
    ],
  },
  {
    name: 'Top Burg Calabresa',
    price: 15.0,
    ingredients: [
      '2 Carne de hambúrguer',
      '2 Ovos',
      'Calabresa',
      'Alface',
      'Tomate',
    ],
  },
  {
    name: 'Top Burg Banana',
    price: 15.0,
    ingredients: [
      '2 Carne de hambúrguer',
      '2 Ovos',
      'Banana',
      'Alface',
      'Tomate',
    ],
  },
  {
    name: 'Top Burg Salsicha',
    price: 15.0,
    ingredients: [
      '2 Carne de hambúrguer',
      '2 Ovos',
      'Salsicha',
      'Alface',
      'Tomate',
    ],
  },
  {
    name: 'Top Burg Especial',
    price: 20.0,
    ingredients: [
      'Carne de hambúrguer',
      'Ovo',
      'Bacon',
      'Calabresa',
      'Presunto',
      'Salsicha',
      'Banana',
      'Queijo coalho',
      'Queijo mussarela',
      'Cheddar',
      'Alface',
      'Tomate',
    ],
  },
];

export const pizzaCombos = [
  {
    name: 'Especial Bacon + Pet de 1,5L',
    price: 50.0,
    ingredients: [
      'Molho',
      'Bacon',
      'Cebolas',
      'Azeitonas',
      'Mussarela',
      'Tomate',
      'Orégano',
      'Milho',
    ],
  },
  {
    name: 'Mussarela + Pet de 1,5L',
    price: 40.0,
    ingredients: ['Molho', 'Mussarela', 'Tomate', 'Orégano', 'Azeitona'],
  },
  {
    name: 'Portuguesa + Pet de 1,5L',
    price: 40.0,
    ingredients: [
      'Mussarela',
      'Molho',
      'Presunto',
      'Ovo',
      'Pimentão',
      'Tomate',
      'Orégano',
      'Cebola',
      'Milho',
      'Azeitona',
    ],
  },
  {
    name: 'Calabresa + Pet de 1,5L',
    price: 40.0,
    ingredients: [
      'Molho',
      'Calabresa',
      'Mussarela',
      'Tomate',
      'Orégano',
      'Milho',
    ],
  },
];
